global:
  scrape_interval: 15s      # Default scrape interval for all job
  evaluation_interval: 15s  # Default evaluation interval for rules

remote_write:
  - url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push
    basic_auth:
      username: 2362479  # Your Grafana Cloud username
      password: glc_eyJvIjoiMTM5NDM1NiIsIm4iOiJzdGFjay0xMjE5MTIwLWFsbG95LWNtcHQyNTAwIiwiayI6IjRiOTg2ZUJ0V0ZxaDk2M0RuV3gzNXAyZSIsIm0iOnsiciI6InByb2QtY2EtZWFzdC0wIn19  # Your Grafana Cloud API key



rule_files:
  - /etc/prometheus/rules/ml_alerts.yml  # Path to alert rules file 

scrape_configs:
  - job_name: 'ml-app'
    scrape_interval: 5s     # Scrape every 5 seconds
    static_configs:
      - targets: ['ml-app:5001']  # Target for the ML API

  - job_name: 'prometheus'
    scrape_interval: 10s   # Scrape every 10 seconds
    static_configs:
      - targets: ['localhost:9090'] # Target for Prometheus itself

  - job_name: 'model-training'
    scrape_interval: 5s     # Scrape every 5 seconds
    metrics_path: /metrics  # PAth where the metrics are exposed
    static_configs:
      - targets: ['train:8003'] # Target for the model training service
  
  - job_name: 'regression_monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8004'] # Target for the regression monitoring service


