groups:
  - name: ml_alerts
    rules:
      - alert: HighPredictionErrorRate
        expr: rate(prediction_errors_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High prediction error rate (> 10%)"
          description: "Prediction API error rate is {{ $value | humanizePercentage }} over the last 1 minutes."

      - alert: SlowPredictionResponse
        expr: histogram_quantile(0.95, rate(prediction_latency_seconds_bucket[5m])) > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Slow prediction response time"
          description: "95th percentile response time for model {{ $labels.model_version }} is {{ $value }}s (>1s threshold)."